version: '3.1'
services:
  
  db:
    image: postgres:11.2-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345qw
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: coad
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    volumes: 
      - ./bkp:/var/lib/pgadmin/storage/
    ports:
      - 9090:80
    environment:
      PGADMIN_DEFAULT_EMAIL: weslei.souza@amcom.com.br
      PGADMIN_DEFAULT_PASSWORD: adminadmin
    depends_on:
      - db

  redis:
    image: redis:5.0.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data/db
  
networks:
  default:
    external:
      name: coad-network

volumes:
  redisdata:
