version: '3.1'
services:
  
  nginx:
    build: .
    ports:
      - 80:80
    depends_on:
      - backend
      # - frontend
    environment:
      SERVER_NAME: localhost

  db:
    image: postgres:11.2-alpine
    restart: always
    env_file: ./.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data    
    ports:
      - 5432:5432
    

  backend:
    build: ./backend/.
    # http://docs.gunicorn.org/en/latest/design.html#how-many-workers
    # http://docs.gunicorn.org/en/latest/settings.html#worker-class
    command: "gunicorn config.wsgi:application --bind=0.0.0.0:8000 -w 8"
    env_file: ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  redis:
    image: redis:5.0.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data/db
  
networks:
  default:
    external:
      name: coad-network

volumes:
  redisdata:
